version: '3.8'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: nyc
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - SPARK_JAVA_OPTS=-Dspark.hadoop.fs.s3a.endpoint=http://minio:9000
    volumes:
      - ./spark:/spark
    depends_on:
      - minio
      - postgres

  airflow:
    image: puckel/docker-airflow:1.10.9
    environment:
      - LOAD_EX=n
      - EXECUTOR=SequentialExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    depends_on:
      - postgres

  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
